[project]
name = "apps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible-vault>=4.1.0",
    "holidays>=0.83",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.44",
    "typer>=0.20.0",
]

[project.scripts]
apps = "apps.apps:main"

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "apps"
module-root = ""
