name: Lint Code Base
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install pipx
        run: python -m pip install --user pipx
      - name: Run ruff check
        run: pipx run ruff check --output-format=github ./
      - name: Run ruff format check
        run: pipx run ruff format --check --diff ./
