name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Poetry
        shell: bash
        run: |
            curl -sSL https://install.python-poetry.org | python3 -
            echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install dev libraries via sudo apt-get
        run: |
          sudo apt-get update -y
          sudo apt-get install -y -f --no-install-recommends \
            libkrb5-dev \
            libcurl4-openssl-dev \
            librtmp-dev
          sudo apt-get clean
      - name: Install dependencies via poetry
        shell: bash
        run: poetry install
      - name: Run tests
        run: pytest